# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: mysql2
  database: wooul_dev2
  host: localhost
  username: wooul
  password: 'wqxyy1985'
  encoding: 'utf8'

cms_development:
  adapter: mysql2
  database: wooul_dev2
  host: localhost
  username: wooul
  password: 'wqxyy1985'
  encoding: 'utf8'


production:
  adapter: mysql2 
  database: wooul_dev2 
  host: localhost
  username: wooul
  password: 'wqxyy1985'
  encoding: 'utf8'
#  database: wooul_dev2
#  host: localhost
#
cms_production:
  adapter: mysql2 
  database: wooul_dev2  
  host: localhost  
  username: wooul
  password: 'wqxyy1985'
  encoding: 'utf8'
#  timeout: 5000
